name: 아이디어 제안 Idea Suggest
description: 아이디어 제안을 이슈로 등록하는 템플릿입니다. Suggest a new idea for improving eGovFrame.
title: "[아이디어 제안(Idea Suggest)]: "
labels: ["idea"]
assignees:
  - yongfire38
body:
  - type: markdown
    attributes:
      value: |
        참가구분 (Participation Category)
