name: 아이디어 제안 Idea Suggest
description: 아이디어 제안을 이슈로 등록하는 템플릿입니다. Suggest a new idea for improving eGovFrame.
title: "[아이디어 제안(Idea Suggest)]: "
labels: ["idea"]
assignees:
  - yongfire38
body:
  - type: textarea
    id: solution
    attributes:
      label: 솔루션 상세 Solution Details
      description: 위 기능을 구현하는데 도움이 되는 기술내용이 있으면 적어 주세요. If you have any technical details to help us implement the above features, please let us know.
      placeholder: 위 기능을 구현하는데 도움이 되는 기술내용은 다음과 같습니다. Here are some technical details to help you implement the above features.
  - type: markdown
    attributes:
      value: |
        ## 참가구분 (Participation Category)
- [ ] 개인 (Individuals)
- [ ] 단체 (Organization)

## 참가자 (단체인 경우 대표자 1인)
| 성명 (Name)	|   	|생년월일 (Date of birth)  	|   	|
|----------	|---	|---	|---	|
| **연락처(Contact)**   	|   	| **E-mail 주소(E-mail address)**  	|   	|

|  단체명 (Organization Name) 	|해당시 작성 (Fill if applicable)  	|
|---	|---	|
|  **팀원성명 (Team Member Names)** 	| **해당 시 작성, 대표자 제외 (Excluding representative)** 	|

---
위와 같이 「전자정부 표준프레임워크 컨트리뷰션 - 아이디어 제안부문」에 참가를 
신청합니다.

2024년 　  월  　    일   
신청인 :  　  (서명 또는 날인)   
**한국지능정보사회진흥원 귀하**

---
## 개인정보의 수집·이용에 관한 사항
 
「전자정부 표준프레임워크 컨트리뷰션 아이디어 제안」 관련하여 아래와 같이 귀하의 개인정보를  
수집·이용하기 위해 「개인정보보호법」제15조에 따라 관련 사항을 고지하오니 동의하여 주시기 바랍니다.

- 개인정보의 수집·이용 목적 : 공모전 접수, 심사, 발표, 시상, 당선작 공개 시 본인 확인 및 안내
- 수집·이용할 개인정보 항목 : 성명, 생년월일, 연락처(휴대 전화번호), 주소, 이메일 주소
- 개인정보의 보유, 이용기간 : 공모전 심사 및 우수작 시상 등 관련 정보의 수집·이용목적이 달성되는 즉시 파기  

 귀하는 상기 내용에 대해 동의하지 않을 수 있으나, 미동의시 심사·선정·결과발표 등 향후 절차에 
있어 부득이하게 제한을 받을 수 있습니다.

- [ ] **동의함**
- [ ] **동의안함**

---
## 아이디어 제안 참가 유의사항

가. 선정된 우수작은 반환하지 않으며, 주최/주관기관의 홍보 목적으로 외부에 공개될 수 있습니다.   
나. 제안내용은 저작권, 소유권, 대여권 등 법적 문제가 없어야 하며, 이와 관련된 분쟁은 신청자에게 
모든 책임이 있습니다.   
다. 단체(팀) 참가의 경우, 팀명과 팀원의 이름을 명시해야 하며, 누락 및 오기재로 인해 생기는 
불이익은 주최/주관사가 책임지지 않습니다.   
라. 아래 사항을 준수하여, **지정양식 3매 이내([서식2] 아이디어 제안서)**로 제출해주시기 바랍니다.   

- 제출파일명 : ‘전자정부 표준프레임워크 아이디어 공모전_성명(또는 단체명)’
- 제  출  처 : 한국지능정보사회진흥원 전자정부 표준프레임워크 업무 담당자(ybnkang@nia.or.kr)
---
- 글자체 : 맑은고딕, 11pt, 장평 100%, 자간 0%
- 문단모양 : 본문 줄 간격 160~180%
- 용지여백 : 위쪽/아래쪽 15mm, 왼/오른쪽 20mm, 머리말/꼬리말 10m
---

# [서식 2] 아이디어 제안서

## 기획 개요

|아이디어명   	|   	|
|---	|---	|
|**아이디어 요약**   	| _과제 내용을 300자 이내로 간결하게 요약 및 정의_   	|

## 기획 내용

|제안배경   	|  _아이디어를 제안하게 된 배경 및 필요성_ 	|
|:---	|:---	|
|**제안내용**   	| ___제안 아이디어의 구체적인 내용을 설명 기술___   	|
|**기대효과**   	| ___아이디어의 실현 가능성과 예상되는 기대효과를 제시___   	|
|**자유기술**   	| ___추가 기재하고 싶은 항목 및 내용 자유롭게 기제___   	|
|**참고문헌**   	| ___참고문헌이 있는 경우 작성___   	|
